import { getDb } from './client';

const db = getDb();

db.run(`CREATE TABLE IF NOT EXISTS dealflow_users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN('partner','analyst')), password_hash TEXT NOT NULL, created_at TEXT DEFAULT(datetime('now')), last_login TEXT)`);
db.run(`CREATE TABLE IF NOT EXISTS pages (slug TEXT PRIMARY KEY, type TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, tags TEXT DEFAULT '[]', created_at TEXT DEFAULT(datetime('now')), updated_at TEXT DEFAULT(datetime('now')), created_by TEXT REFERENCES dealflow_users(id), updated_by TEXT REFERENCES dealflow_users(id))`);
db.run(`CREATE TABLE IF NOT EXISTS page_contributions (id INTEGER PRIMARY KEY AUTOINCREMENT, page_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, user_id TEXT REFERENCES dealflow_users(id), contribution_type TEXT NOT NULL CHECK(contribution_type IN('created','updated','enriched','merged')), content_snapshot TEXT NOT NULL, content_hash TEXT NOT NULL, timestamp TEXT DEFAULT(datetime('now')), source TEXT NOT NULL CHECK(source IN('manual','hog_auto','meeting_notes','system')))`);
db.run(`CREATE TABLE IF NOT EXISTS analyst_assignments (id INTEGER PRIMARY KEY AUTOINCREMENT, analyst_id TEXT NOT NULL REFERENCES dealflow_users(id), page_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, assigned_by TEXT NOT NULL REFERENCES dealflow_users(id), assigned_at TEXT DEFAULT(datetime('now')), UNIQUE(analyst_id, page_slug))`);
db.run(`CREATE TABLE IF NOT EXISTS entity_merges (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, merged_from TEXT NOT NULL, merge_strategy TEXT NOT NULL CHECK(merge_strategy IN('latest','consensus','partner_wins','timeline_append')), merged_at TEXT DEFAULT(datetime('now')), merged_content TEXT NOT NULL, conflict_resolution TEXT)`);
db.run(`CREATE TABLE IF NOT EXISTS timeline_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, page_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, timestamp TEXT NOT NULL, event_type TEXT NOT NULL, description TEXT NOT NULL, source TEXT NOT NULL, source_url TEXT, metadata TEXT DEFAULT '{}', added_by TEXT REFERENCES dealflow_users(id), added_at TEXT DEFAULT(datetime('now')))`);
db.run(`CREATE TABLE IF NOT EXISTS hog_signals (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, signal_type TEXT NOT NULL CHECK(signal_type IN('mention','hiring','funding','product','press')), source TEXT NOT NULL, content TEXT NOT NULL, url TEXT, timestamp TEXT NOT NULL, engagement TEXT DEFAULT '{}', fetched_at TEXT DEFAULT(datetime('now')), relevance_score REAL)`);
db.run(`CREATE TABLE IF NOT EXISTS entity_links (id INTEGER PRIMARY KEY AUTOINCREMENT, from_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, to_slug TEXT NOT NULL REFERENCES pages(slug) ON DELETE CASCADE, link_type TEXT NOT NULL CHECK(link_type IN('works_at','founded','invested_in','advises','attended','knows')), created_at TEXT DEFAULT(datetime('now')), created_by TEXT REFERENCES dealflow_users(id), metadata TEXT DEFAULT '{}', UNIQUE(from_slug, to_slug, link_type))`);
db.run(`CREATE TABLE IF NOT EXISTS dream_cycle_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, phase TEXT NOT NULL, started_at TEXT DEFAULT(datetime('now')), completed_at TEXT, status TEXT NOT NULL CHECK(status IN('running','completed','failed')), pages_processed INTEGER DEFAULT 0, signals_added INTEGER DEFAULT 0, errors TEXT DEFAULT '[]', metadata TEXT DEFAULT '{}')`);

console.log('✓ Database schema created successfully');
